# Generated by Django 5.1.2 on 2024-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentconfig',
            options={},
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='client_secret',
            field=models.CharField(max_length=255),
        ),
    ]
