# Generated by Django 5.1.2 on 2024-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0010_poltaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltaker',
            name='completed_surveys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poltaker',
            name='inprogress_surveys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poltaker',
            name='pending_surveys',
            field=models.IntegerField(default=0),
        ),
    ]
