# Generated by Django 5.1.2 on 2024-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0017_passwordreset_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Open Text'), ('yesno', 'Yes/No')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
