# Generated by Django 5.1.2 on 2024-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0018_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Open Text'), ('yesno', 'Yes/No')], max_length=10)),
                ('options', models.TextField(blank=True)),
            ],
        ),
    ]
