# Generated by Django 5.1.2 on 2024-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0020_poltaker_street_poltaker_city_poltaker_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poltaker',
            name='Street',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='poltaker',
            name='city',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
