# Generated by Django 5.1.2 on 2024-11-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0021_alter_poltaker_street_alter_poltaker_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltaker',
            name='password_needs_update',
            field=models.BooleanField(default=True),
        ),
    ]
