# Generated by Django 5.1.2 on 2024-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0022_poltaker_password_needs_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poltaker',
            name='password_needs_update',
        ),
        migrations.AddField(
            model_name='poltaker',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
