# Generated by Django 5.1.2 on 2024-11-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0024_usercontactlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactlist',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='zipcode',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='party_preference',
            field=models.CharField(choices=[('Republican', 'Republican'), ('Democrat', 'Democrat'), ('Independent', 'Independent')], max_length=50),
        ),
    ]
