# Generated by Django 5.1.2 on 2024-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0027_usercontactlist_latitude_usercontactlist_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltaker',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
