# Generated by Django 5.1.2 on 2024-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0028_poltaker_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactlist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='pct_nbr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='reg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='state_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='voter_nbr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontactlist',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='party_preference',
            field=models.CharField(blank=True, choices=[('Republican', 'Republican'), ('Democrat', 'Democrat'), ('Independent', 'Independent')], max_length=50),
        ),
    ]
