# Generated by Django 5.1.2 on 2024-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0029_usercontactlist_address_usercontactlist_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactlist',
            name='address',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='address2',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='city',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='country',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='district',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='party_preference',
            field=models.CharField(blank=True, choices=[('Republican', 'Republican'), ('Democrat', 'Democrat'), ('Independent', 'Independent'), ('NA', 'NA')], default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='pct_nbr',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='phone',
            field=models.CharField(blank=True, default='NA', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='state',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='state_id',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='street',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='title',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='voter_nbr',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='ward',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactlist',
            name='zipcode',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
    ]
