# Generated by Django 5.1.2 on 2024-11-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0030_alter_usercontactlist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactlist',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending')], default='in_progress', max_length=20),
        ),
    ]
