# Generated by Django 5.1.2 on 2024-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0032_alter_usercontactlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactlist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=50),
        ),
    ]
