# Generated by Django 5.1.2 on 2024-11-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0034_usercontactsearch_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontactsearch',
            old_name='precinct_number',
            new_name='pct_nbr',
        ),
    ]
