# Generated by Django 5.1.2 on 2024-12-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkapp', '0035_rename_precinct_number_usercontactsearch_pct_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltaker',
            name='deny_surveys',
            field=models.IntegerField(default=0),
        ),
    ]
