# Generated by Django 5.1.2 on 2024-11-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walkapp', '0026_usercontactsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('polltaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_surveys', to='walkapp.poltaker')),
                ('questions', models.ManyToManyField(related_name='surveys', to='walkapp.generalquestion')),
            ],
        ),
    ]
