# Generated by Django 5.1.2 on 2024-11-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
        ('walkapp', '0026_usercontactsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='polltaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='walkapp.poltaker'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
