# Generated by Django 5.1.2 on 2024-11-06 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_survey_created_by_survey_questions_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='responses',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
