# Generated by Django 5.1.2 on 2024-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_remove_surveyresponse_answer_text_and_more'),
        ('walkapp', '0026_usercontactsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='contacts',
            field=models.ManyToManyField(related_name='surveys', to='walkapp.usercontactlist'),
        ),
    ]
