# Generated by Django 5.1.2 on 2024-11-07 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_survey_contacts'),
        ('walkapp', '0026_usercontactsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='walkapp.usercontactlist'),
            preserve_default=False,
        ),
    ]
