# Generated by Django 5.1.2 on 2024-11-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0006_surveyresponse_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='contact',
        ),
    ]
