# Generated by Django 5.1.2 on 2024-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0008_surveyresponse_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
