# Generated by Django 5.1.2 on 2024-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0009_surveyresponse_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
