# Generated by Django 5.1.2 on 2024-11-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0011_alter_surveyresponse_polltaker'),
        ('walkapp', '0027_usercontactlist_latitude_usercontactlist_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='polltaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkapp.poltaker'),
        ),
    ]
