# Generated by Django 5.1.2 on 2024-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0015_survey_survey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], default='assigned', max_length=20),
        ),
    ]
