# Generated by Django 5.1.2 on 2024-11-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0017_alter_survey_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
    ]
