# Generated by Django 5.1.2 on 2024-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0019_survey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
