# Generated by Django 5.1.2 on 2024-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0020_survey_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_token',
            field=models.CharField(default=45, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
