# Generated by Django 5.1.2 on 2024-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0021_alter_survey_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_token',
            field=models.CharField(max_length=15),
        ),
    ]
