# Generated by Django 5.1.2 on 2024-12-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0022_alter_survey_survey_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='denial_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
