# Generated by Django 5.1.2 on 2024-12-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0023_survey_denial_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='denial_reason',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
