# Generated by Django 5.1.2 on 2024-12-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0025_survey_rejections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='rejections',
        ),
    ]
